
services:
  api:
    build: ./services/api
    container_name: poquotator-api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - mailhog
      - erp
    volumes:
      - ./services/api:/app

  erp:
    build: ./services/erp
    container_name: poquotator-erp
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - ./services/erp:/app

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: poquotator-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
