services:
  api:
    build: ./services/api
    container_name: poquotator-api
    env_file: .env
    environment:
      APP_PORT: "8000"
      SMTP_HOST: mailhog
      SMTP_PORT: "1025"
      TRIAGE_EMAIL: triage@example.com
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - mailhog
      - erp
    volumes:
      - ./services/api:/app

  erp:
    build: ./services/erp
    container_name: poquotator-erp
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - ./services/erp:/app

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: poquotator-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  db:
    image: postgres:16-alpine
    container_name: poquotator-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-poquotator}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-poquotator}
      POSTGRES_DB: ${POSTGRES_DB:-poquotator}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./services/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer:4
    container_name: poquotator-adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
