version: "3.9"


services:
api:
build: ./services/api
container_name: poquotator_api
env_file:
- ./.env
ports:
- "8000:8000"
depends_on:
- redis
- mailhog
- erp-mock
volumes:
- ./services/api/app:/app


worker:
build: ./services/worker
container_name: poquotator_worker
env_file:
- ./.env
depends_on:
- redis
volumes:
- ./services/worker/worker:/worker


redis:
image: redis:7-alpine
container_name: poquotator_redis
ports:
- "6379:6379"


# Local email testing server with REST API
mailhog:
image: mailhog/mailhog:v1.0.1
container_name: poquotator_mailhog
ports:
- "8025:8025" # UI
- "1025:1025" # SMTP


# Mock ERP for quotes & accounts
erp-mock:
build: ./services/erp-mock
container_name: poquotator_erp_mock
ports:
- "9000:9000"